In [2]:
import pandas as pd
import os

# easySHARE

## Benchmarks

In [2]:
path_to_results = os.getcwd() + "/results/easySHARE/"


index_pd = pd.MultiIndex.from_product(
    [
        ["RUMBoost", "TasteNet"],
        ["Functional intercept and slopes", "Functional slopes only", "Functional intercept only","No functional effects"],
    ],
    names=["Model", "Functional effects"],
)

benchmark_table = pd.DataFrame({},
    columns=[
        "MAE",
        "EMAE",
        "MCEL",
        "Comput. time [s]",
    ],
    index=index_pd,
    
)



for model in ["RUMBoost", "TasteNet"]:
    for func_int in ["True", "False"]:
        for func_params in ["True", "False"]:
            results = pd.read_csv(
                f"{path_to_results}{model}/results_dict_fi{func_int}_fp{func_params}.csv"
            )

            benchmark_table.loc[
                (model, f"Functional intercept and slopes" if func_int == "True" and func_params == "True" else
                 f"Functional intercept only" if func_int == "True" else
                 f"Functional slopes only" if func_params == "True" else
                 "No functional effects"),
                ["MAE", "EMAE", "MCEL", "Comput. time [s]"],
            ] = results[["mae_test", "emae_test", "loss_test", "train_time"]].values.round(3)
            benchmark_table["Comput. time [s]"] = benchmark_table["Comput. time [s]"].astype(float).round(2)

benchmark_table

                                            MAE   EMAE   MCEL  \
Model    Functional effects
RUMBoost Functional intercept and slopes  1.369  0.146  0.251
         Functional slopes only            1.37  0.146  0.251
         Functional intercept only        1.368  0.146  0.251
         No functional effects            1.414  0.151   0.26
TasteNet Functional intercept and slopes  1.366  0.145   0.25
         Functional slopes only           1.368  0.147  0.251
         Functional intercept only        1.372  0.147  0.252
         No functional effects            1.421  0.153  0.261

                                          Comput. time [s]
Model    Functional effects
RUMBoost Functional intercept and slopes            169.30
         Functional slopes only                     178.04
         Functional intercept only                  241.08
         No functional effects                      806.52
TasteNet Functional intercept and slopes            178.42
         Functional slopes only                     214.69
         Functional intercept only                  172.82
         No functional effects                       35.22

In [3]:
benchmark_table.to_latex("results/easySHARE/benchmark_table.tex", index=True, float_format="%.3f", escape=False,
    column_format="lrrrr",)

## Variables in the model

In [4]:
from constants import alt_spec_features, PATH_TO_DATA

all_alt_spec_features = []
for k, v in alt_spec_features["easySHARE"].items():
    all_alt_spec_features.extend(v)

df = pd.read_csv(PATH_TO_DATA["easySHARE"])
socio_demo_chars = [
    col
    for col in df.columns
    if col not in all_alt_spec_features
    and col not in ["mergeid", "hhid", "coupleid", "depression_scale"]
]

In [5]:
socio_demo_chars

['female',
 'age',
 'hhsize',
 'nb_children',
 'hh_net_income',
 'born_in_itw_country_yes',
 'education_level_1',
 'education_level_2',
 'education_level_3',
 'education_level_4',
 'education_level_5',
 'education_level_6',
 'education_none',
 'education_studying',
 'marital_status_married',
 'marital_status_reg_partnership',
 'marital_status_separated',
 'marital_status_single',
 'marital_status_widowed',
 'partnerinhh_yes',
 'mother_alive_yes',
 'father_alive_yes',
 'help_outside_hh_yes',
 'smoking_yes',
 'ever_smoked_yes',
 'vigorous_activity_more_than_once_a_week',
 'vigorous_activity_never',
 'vigorous_activity_once_three_times_a_month',
 'job_situation_homemaker',
 'job_situation_other',
 'job_situation_retired',
 'job_situation_unable_to_work',
 'job_situation_unemployed',
 'household_ends_meet_fairly_easily',
 'household_ends_meet_with_great_difficulty',
 'household_ends_meet_with_some_difficulty',
 'has_citizenship_yes',
 'country_BE',
 'country_BG',
 'country_CH',
 'country_CY',
 'country_CZ',
 'country_DE',
 'country_DK',
 'country_EE',
 'country_ES',
 'country_FI',
 'country_FR',
 'country_GR',
 'country_HR',
 'country_HU',
 'country_IE',
 'country_IL',
 'country_IT',
 'country_LT',
 'country_LU',
 'country_LV',
 'country_MT',
 'country_NL',
 'country_PL',
 'country_PT',
 'country_RO',
 'country_SE',
 'country_SI',
 'country_SK']

In [6]:
all_alt_spec_features

['chronic_mod',
 'nb_doctor_visits',
 'maxgrip',
 'daily_activities_index',
 'instrumental_activities_index',
 'mobilityind',
 'lgmuscle',
 'grossmotor',
 'finemotor',
 'recall_1',
 'recall_2',
 'bmi',
 'sphus_fair',
 'sphus_good',
 'sphus_poor',
 'sphus_very_good',
 'hospitalised_last_year_yes',
 'nursing_home_last_year_yes_permanently',
 'nursing_home_last_year_yes_temporarily']

## Alt-spec feature names

In [7]:
feature_names = {
    "bmi": "BMI",
    "chronic_mod": "Number of chronic conditions",
    "daily_activities_index": "Daily activities index",
    "finemotor": "Fine motor skills",
    "grossmotor": "Gross motor skills",
    "hospitalised_last_year_yes": "Hospitalised last year",
    "lgmuscle": "Large muscle skills",
    "maxgrip": "Max grip strength",
    "mobilityind": "Mobility index",
    "nursing_home_last_year_yes_permanently": "Nursing home last year (permanently)",
    "nursing_home_last_year_yes_temporarily": "Nursing home last year (temporarily)",
    "recall_1": "Recall 1",
    "recall_2": "Recall 2",
    "sphus_fair": "Self-perceived health - fair",
    "sphus_good": "Self-perceived health - good",
    "sphus_poor": "Self-perceived health - poor",
    "sphus_very_good": "Self-perceived health - very good",
    "sphus_very_poor": "Self-perceived health - very poor",
    "instrumental_activities_index": "Instrumental activities index",
    "nb_doctor_visits": "Number of doctor visits",
}

print([key for key in feature_names.values()])

['BMI', 'Number of chronic conditions', 'Daily activities index', 'Fine motor skills', 'Gross motor skills', 'Hospitalised last year', 'Large muscle skills', 'Max grip strength', 'Mobility index', 'Nursing home last year (permanently)', 'Nursing home last year (temporarily)', 'Recall 1', 'Recall 2', 'Self-perceived health - fair', 'Self-perceived health - good', 'Self-perceived health - poor', 'Self-perceived health - very good', 'Self-perceived health - very poor', 'Instrumental activities index', 'Number of doctor visits']

## hyperparameters

In [8]:
import os
import pandas as pd

path_to_results = os.getcwd() + "/results/easySHARE/"

multi_columns = pd.MultiIndex.from_product(
    [
        ["RUMBoost", "TasteNet"],
        [
            "Functional intercept and slopes",
            "Functional slopes only",
            "Functional intercept only",
            "No functional effects",
        ],
    ],
)

indices = [
    "Validation MCEL",
    "Time [s]",
    "best_iteration",
    "lambda_l1",
    "lambda_l2",
    "num_leaves",
    "feature_fraction",
    "bagging_fraction",
    "bagging_freq",
    "min_data_in_leaf",
    "max_bin",
    "min_sum_hessian_in_leaf",
    "min_gain_to_split",
    "batch_size",
    "learning_rate",
    "dropout",
    "act_func",
    "batch_norm",
    "layer_sizes",
]

hyp_results = pd.DataFrame({}, columns=multi_columns, index=indices)

search_space = {
    "Search space": [
        "-",
        "-",
        r"Max 3000 iterations \slash 200 epochs",
        r"$[10^{-8}, 1]$",
        r"$[10^{-8}, 1]$",
        r"$[2, 256]$",
        r"$[0.4, 1]$",
        r"$[0.4, 1]$",
        r"$[1, 7]$",
        r"$[1, 200]$",
        r"$[64, 511]$",
        r"$[10^{-8}, 10]$",
        r"$[10^{-8}, 10]$",
        r"\{256, 512\}",
        r"$[0.0001, 0.01]$",
        r"$[0.0, 0.9]$",
        r"\{ReLU, Sigmoid, Tanh\}",
        r"\{True, False\}",
        r"\{[32], [64], [128], [32, 32], [64, 64], [128, 128], [64, 128], [128, 64], [64, 128, 64]\}",
    ]
}

distribution = {
    "Distribution": [
        "-",
        "-",
        "-",
        "Log-uniform",
        "Log-uniform",
        "Discrete uniform",
        "Uniform",
        "Uniform",
        "Discrete uniform",
        "Discrete uniform",
        "Discrete uniform",
        "Log-uniform",
        "Log-uniform",
        "Categorical",
        "Log-uniform",
        "Uniform",
        "Categorical",
        "Categorical",
        "Categorical",
    ]
}

search_space_series = pd.Series(search_space["Search space"], index=hyp_results.index)
distribution_series = pd.Series(distribution["Distribution"], index=hyp_results.index)

hyp_results.insert(0, ("", "Search space"), search_space_series)
hyp_results.insert(1, ("", "Distribution"), distribution_series)


for model in ["RUMBoost", "TasteNet"]:
    for func_int in ["True", "False"]:
        for func_params in ["True", "False"]:
            results_dict = pd.read_pickle(
                f"{path_to_results}{model}/best_params_fi{func_int}_fp{func_params}.pkl"
            )
            results = pd.DataFrame(results_dict.values(), index=results_dict.keys())

            hyp_results.loc[
                results.index,
                (
                    model,
                    (
                        "Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            "Functional intercept only"
                            if func_int == "True"
                            else (
                                "Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = results.values.reshape(-1)

            if func_int == "False" and func_params == "False":
                hyp_results.loc["dropout", (model, "No functional effects")] = 0
                hyp_results.loc["batch_norm", (model, "No functional effects")] = "False"
                hyp_results.loc["layer_sizes", (model, "No functional effects")] = "-"
                hyp_results.loc["lambda_l1", (model, "No functional effects")] = 0
                hyp_results.loc["lambda_l2", (model, "No functional effects")] = 0
                hyp_results.loc["act_func", (model, "No functional effects")] = "-"

for model in ["RUMBoost", "TasteNet"]:
    for func_int in ["True", "False"]:
        for func_params in ["True", "False"]:
            opt_and_cel = pd.read_table(
                f"{path_to_results}{model}/hyper_search_info_fi{func_int}_fp{func_params}.txt",
                header=None,
                index_col=0,
            )
            opt_and_cel_dict = {}
            for element in opt_and_cel.index.to_list():
                ind_and_value = element.split(":")
                opt_and_cel_dict[ind_and_value[0]] = float(ind_and_value[1].strip())
            opt_and_cel = pd.DataFrame(
                opt_and_cel_dict.values(),
                index=opt_and_cel_dict.keys(),
                columns=["values"],
            )
            hyp_results.loc[
                "Time [s]",
                (
                    model,
                    (
                        "Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            "Functional intercept only"
                            if func_int == "True"
                            else (
                                "Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = opt_and_cel.loc["Optimisation time"].values.round(0)
            hyp_results.loc[
                "Validation MCEL",
                (
                    model,
                    (
                        f"Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            f"Functional intercept only"
                            if func_int == "True"
                            else (
                                f"Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = opt_and_cel.loc["Best value"].values.round(3)

hyp_results = hyp_results.rename(index={"best_iteration": "Best iteration/epoch"})
hyp_results = hyp_results.fillna("-")
hyp_results.loc["learning_rate", ("RUMBoost")] = 0.05

In [9]:
hyp_results

                                                                            \
                                                              Search space
Validation MCEL                                                          -
Time [s]                                                                 -
Best iteration/epoch                 Max 3000 iterations \slash 200 epochs
lambda_l1                                                   $[10^{-8}, 1]$
lambda_l2                                                   $[10^{-8}, 1]$
num_leaves                                                      $[2, 256]$
feature_fraction                                                $[0.4, 1]$
bagging_fraction                                                $[0.4, 1]$
bagging_freq                                                      $[1, 7]$
min_data_in_leaf                                                $[1, 200]$
max_bin                                                        $[64, 511]$
min_sum_hessian_in_leaf                                    $[10^{-8}, 10]$
min_gain_to_split                                          $[10^{-8}, 10]$
batch_size                                                    \{256, 512\}
learning_rate                                             $[0.0001, 0.01]$
dropout                                                       $[0.0, 0.9]$
act_func                                           \{ReLU, Sigmoid, Tanh\}
batch_norm                                                 \{True, False\}
layer_sizes              \{[32], [64], [128], [32, 32], [64, 64], [128,...

                                                                 RUMBoost  \
                             Distribution Functional intercept and slopes
Validation MCEL                         -                           0.253
Time [s]                                -                          4512.0
Best iteration/epoch                    -                           385.0
lambda_l1                     Log-uniform                        0.520881
lambda_l2                     Log-uniform                        0.000019
num_leaves               Discrete uniform                             3.0
feature_fraction                  Uniform                        0.787585
bagging_fraction                  Uniform                        0.997844
bagging_freq             Discrete uniform                             2.0
min_data_in_leaf         Discrete uniform                           159.0
max_bin                  Discrete uniform                           209.0
min_sum_hessian_in_leaf       Log-uniform                             0.0
min_gain_to_split             Log-uniform                             0.0
batch_size                    Categorical                               -
learning_rate                 Log-uniform                            0.05
dropout                           Uniform                               -
act_func                      Categorical                               -
batch_norm                    Categorical                               -
layer_sizes                   Categorical                               -

                                                                          \
                        Functional slopes only Functional intercept only
Validation MCEL                          0.253                     0.253
Time [s]                                5683.0                    7752.0
Best iteration/epoch                     517.0                     867.0
lambda_l1                             0.000309                       0.0
lambda_l2                                  0.0                  0.000798
num_leaves                                 3.0                      11.0
feature_fraction                      0.707734                  0.492381
bagging_fraction                      0.998197                  0.878719
bagging_freq                               1.0                       1.0
min_data_in_leaf                         173.0                     194.0
max_bin                                  363.0                      95.0
min_sum_hessian_in_leaf               0.097812                  2.234351
min_gain_to_split                     3.630916                  5.169129
batch_size                                   -                         -
learning_rate                             0.05                      0.05
dropout                                      -                         -
act_func                                     -                         -
batch_norm                                   -                         -
layer_sizes                                  -                         -

                                                                     TasteNet  \
                        No functional effects Functional intercept and slopes
Validation MCEL                         0.261                           0.253
Time [s]                              32617.0                         20587.0
Best iteration/epoch                   2259.0                            63.0
lambda_l1                                   0                        0.000001
lambda_l2                                   0                        0.000001
num_leaves                               74.0                               -
feature_fraction                     0.719554                               -
bagging_fraction                     0.863315                               -
bagging_freq                              3.0                               -
min_data_in_leaf                        127.0                               -
max_bin                                 219.0                               -
min_sum_hessian_in_leaf                   0.0                               -
min_gain_to_split                         0.0                               -
batch_size                                  -                             256
learning_rate                            0.05                        0.000306
dropout                                     0                        0.179015
act_func                                    -                         sigmoid
batch_norm                              False                            True
layer_sizes                                 -                         64, 128

                                                                          \
                        Functional slopes only Functional intercept only
Validation MCEL                          0.253                     0.254
Time [s]                               16027.0                   15718.0
Best iteration/epoch                      90.0                      61.0
lambda_l1                             0.000009                  0.000038
lambda_l2                             0.000063                  0.000038
num_leaves                                   -                         -
feature_fraction                             -                         -
bagging_fraction                             -                         -
bagging_freq                                 -                         -
min_data_in_leaf                             -                         -
max_bin                                      -                         -
min_sum_hessian_in_leaf                      -                         -
min_gain_to_split                            -                         -
batch_size                                 256                       256
learning_rate                         0.002347                  0.000302
dropout                               0.286888                   0.13993
act_func                               sigmoid                   sigmoid
batch_norm                               False                      True
layer_sizes                            64, 128                   128, 64


                        No functional effects
Validation MCEL                         0.262
Time [s]                               8879.0
Best iteration/epoch                     22.0
lambda_l1                                   0
lambda_l2                                   0
num_leaves                                  -
feature_fraction                            -
bagging_fraction                            -
bagging_freq                                -
min_data_in_leaf                            -
max_bin                                     -
min_sum_hessian_in_leaf                     -
min_gain_to_split                           -
batch_size                                256
learning_rate                        0.002316
dropout                                     0
act_func                                    -
batch_norm                              False
layer_sizes                                 -

In [10]:
hyp_results.to_latex(
    "results/easySHARE/hyperparameter_results.tex",
    index=True,
    float_format="%.3f",
    escape=False,
    column_format="l" + "r" * (len(hyp_results.columns) - 1),
)

## thresholds

In [11]:
from models_wrapper import TasteNet, RUMBoost
import numpy as np
import lightgbm as lgb
import torch

path_to_results = os.getcwd() + "/results/easySHARE/"

multi_columns = pd.MultiIndex.from_product(
    [
        ["RUMBoost", "TasteNet"],
        [
            "Functional intercept and slopes",
            "Functional slopes only",
            "Functional intercept only",
            "No functional effects",
        ],
    ],
)

indices = pd.Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], name="Thresholds")

thresholds_results = pd.DataFrame({}, columns=multi_columns, index=indices)

for model in ["RUMBoost", "TasteNet"]:
    for func_int in ["True", "False"]:
        for func_params in ["True", "False"]:

            if model == "RUMBoost":
                path = (
                    f"{path_to_results}{model}/model_fi{func_int}_fp{func_params}.json"
                )
                actual_model = RUMBoost()
                actual_model.load_model(path)
                df_zero = pd.DataFrame(
                    np.zeros(len(all_alt_spec_features + socio_demo_chars)).reshape(
                        1, -1
                    ),
                    columns=all_alt_spec_features + socio_demo_chars,
                )
                lgb_zero = lgb.Dataset(df_zero, label=np.zeros(1), free_raw_data=False)
                raw_preds_zero = actual_model.model.predict(lgb_zero, utilities=True)
                actual_model.model.thresholds = torch.tensor(actual_model.model.thresholds).to(torch.device("cuda"))
                thresh = actual_model.model.thresholds - raw_preds_zero
                thresh = thresh.cpu().numpy()  # (J-1,)
            elif model == "TasteNet":
                path = (
                    f"{path_to_results}{model}/model_fi{func_int}_fp{func_params}.pth"
                )
                actual_model = TasteNet()
                actual_model.load_model(path)
                x = torch.zeros(
                    1,
                    len(all_alt_spec_features),
                    device=torch.device("cuda"),
                )
                z = torch.zeros(
                    1,
                    len(socio_demo_chars),
                    device=torch.device("cuda"),
                )
                if func_int == "True" or func_params == "True":
                    b = actual_model.model.params_module(z)  # taste parameters, (N,1)
                else:
                    b = None
                v = actual_model.model.util_module(x, b)  # no softmax here

                thresh = -actual_model.model.ordinal_module(v).detach().cpu().numpy()  # (N, J-1)if func_int == "True":

            thresholds_results.loc[
                :,
                (
                    model,
                    (
                        "Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            "Functional intercept only"
                            if func_int == "True"
                            else (
                                "Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = thresh.round(3)

thresholds_results

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
/home/nicolas-salvade/miniforge3/envs/rumb/lib/python3.11/site-packages/tqdm_joblib/__init__.py:4: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.

                                  RUMBoost                         \
           Functional intercept and slopes Functional slopes only
Thresholds
1                                   -1.019                 -1.003
2                                    0.148                  0.163
3                                    1.033                  1.052
4                                    1.792                  1.806
5                                    2.528                  2.541
6                                    3.262                  3.276
7                                    3.999                  4.013
8                                    4.742                  4.757
9                                     5.56                  5.571
10                                   6.568                  6.572
11                                   7.755                  7.789
12                                    8.89                  8.957

                                                            \
           Functional intercept only No functional effects
Thresholds
1                             -1.865                -1.585
2                             -0.694                -0.454
3                              0.203                 0.413
4                              0.956                 1.137
5                              1.688                 1.846
6                               2.42                 2.556
7                              3.149                 3.268
8                              3.883                 3.986
9                              4.682                 4.775
10                             5.648                 5.711
11                               6.9                 6.978
12                             8.136                 8.366

                                  TasteNet                         \
           Functional intercept and slopes Functional slopes only
Thresholds
1                                   -1.392                 -1.248
2                                   -0.203                 -0.055
3                                    0.678                   0.82
4                                    1.464                  1.594
5                                     2.21                  2.339
6                                     2.94                  3.076
7                                     3.67                  3.804
8                                    4.407                  4.538
9                                    5.219                  5.345
10                                   6.177                  6.302
11                                   7.412                  7.555
12                                   8.971                  9.192


           Functional intercept only No functional effects
Thresholds
1                             -1.865                -1.503
2                             -0.682                -0.365
3                              0.193                 0.465
4                              0.968                   1.2
5                              1.705                 1.909
6                              2.425                 2.585
7                               3.14                   3.3
8                               3.87                 4.019
9                              4.671                 4.784
10                             5.621                 5.727
11                             6.843                 6.957
12                             8.386                  8.57

In [12]:
thresholds_results.to_latex(
    "results/easySHARE/thresholds_results.tex",
    index=True,
    float_format="%.3f",
    escape=False,
    column_format="lrrrrrrrr",
)

# Swissmetro and LPMC

## Benchmarks

In [13]:



index_pd = pd.MultiIndex.from_product(
    [
        ["RUMBoost", "TasteNet"],
        ["Functional intercept and slopes", "Functional slopes only", "Functional intercept only","No functional effects"],
    ],
    names=["Model", "Functional effects"],
)

benchmark_table = pd.DataFrame({},
    columns=pd.MultiIndex.from_product(
        [
            ["SwissMetro", "LPMC"],
            ["CEL", "Comput. time [s]"],
        ],
    ),
   index=index_pd,
)



for dataset in ["LPMC", "SwissMetro"]:
    path_to_results = os.getcwd() + f"/results/{dataset}/"
    for model in ["RUMBoost", "TasteNet", "GBDT", "DNN"]:
        for func_int in ["True", "False"]:
            for func_params in ["True", "False"]:
                if model in ["GBDT", "DNN"] and func_params == "True":
                    continue
                results = pd.read_csv(
                    f"{path_to_results}{model}/results_dict_fi{func_int}_fp{func_params}.csv"
                )

                benchmark_table.loc[
                    (model, f"Functional intercept and slopes" if func_int == "True" and func_params == "True" else
                    f"Functional intercept only" if func_int == "True" else
                    f"Functional slopes only" if func_params == "True" else
                    "No functional effects"),
                    (dataset, ["CEL", "Comput. time [s]"]),
                ] = results[["loss_test", "train_time"]].values.round(3)
                benchmark_table[(dataset, "Comput. time [s]")] = benchmark_table[(dataset, "Comput. time [s]")].astype(float).round(2)

benchmark_table

                                         SwissMetro                    LPMC  \
                                                CEL Comput. time [s]    CEL
Model    Functional effects
RUMBoost Functional intercept and slopes      0.614             9.02  0.681
         Functional slopes only               0.679             7.32  0.688
         Functional intercept only             0.63             1.76  0.668
         No functional effects                0.786             1.54  0.824
TasteNet Functional intercept and slopes      0.619             5.35   0.68
         Functional slopes only               0.669             6.10  0.691
         Functional intercept only            0.662            13.25  0.687
         No functional effects                0.854             8.57  0.842
GBDT     Functional intercept only            0.525            14.71  0.655
         No functional effects                0.622            18.92  0.805
DNN      Functional intercept only            0.575             6.42  0.686
         No functional effects                0.684             2.97   0.82


                                         Comput. time [s]
Model    Functional effects
RUMBoost Functional intercept and slopes            20.77
         Functional slopes only                     16.98
         Functional intercept only                   3.36
         No functional effects                       3.36
TasteNet Functional intercept and slopes            81.01
         Functional slopes only                     44.17
         Functional intercept only                  47.19
         No functional effects                      32.20
GBDT     Functional intercept only                   8.82
         No functional effects                      15.30
DNN      Functional intercept only                  16.40
         No functional effects                      40.87

In [14]:
benchmark_table.to_latex("results/SwissMetro/benchmark_table.tex", index=True, float_format="%.3f", escape=False,
    column_format="lrrrr",)

## Variables in the model

In [15]:
from constants import alt_spec_features, PATH_TO_DATA_TRAIN
from utils import pkl_to_df


all_alt_spec_features = []
for k, v in alt_spec_features["SwissMetro"].items():
    all_alt_spec_features.extend(v)

df = pkl_to_df(PATH_TO_DATA_TRAIN["SwissMetro"])
socio_demo_chars = [
    col
    for col in df.columns
    if col not in all_alt_spec_features
    and col not in ["CHOICE"]
]

In [16]:
socio_demo_chars

['MALE_0',
 'MALE_1',
 'AGE_0',
 'AGE_1',
 'AGE_2',
 'AGE_3',
 'AGE_4',
 'INCOME_0',
 'INCOME_1',
 'INCOME_2',
 'INCOME_3',
 'FIRST_0',
 'FIRST_1',
 'WHO_0',
 'WHO_1',
 'WHO_2',
 'PURPOSE_0',
 'PURPOSE_1',
 'PURPOSE_2',
 'PURPOSE_3',
 'LUGGAGE_0',
 'LUGGAGE_1',
 'LUGGAGE_2',
 'GA_0',
 'GA_1']

In [17]:
all_alt_spec_features

['TRAIN_TT',
 'TRAIN_HE',
 'TRAIN_CO',
 'SM_TT',
 'SM_HE',
 'SM_CO',
 'SM_SEATS',
 'CAR_TT',
 'CAR_CO']

## hyperparameters

In [18]:
import os
import pandas as pd

path_to_results = os.getcwd() + "/results/SwissMetro/"

multi_columns = pd.MultiIndex.from_product(
    [
        ["RUMBoost", "TasteNet"],
        [
            "Functional intercept and slopes",
            "Functional slopes only",
            "Functional intercept only",
            "No functional effects",
        ],
    ],
)

indices = [
    "Validation MCEL",
    "Time [s]",
    "best_iteration",
    "lambda_l1",
    "lambda_l2",
    "num_leaves",
    "feature_fraction",
    "bagging_fraction",
    "bagging_freq",
    "min_data_in_leaf",
    "max_bin",
    "min_sum_hessian_in_leaf",
    "min_gain_to_split",
    "batch_size",
    "learning_rate",
    "dropout",
    "act_func",
    "batch_norm",
    "layer_sizes",
]

hyp_results = pd.DataFrame({}, columns=multi_columns, index=indices)

search_space = {
    "Search space": [
        "-",
        "-",
        r"Max 3000 iterations \slash 200 epochs",
        r"$[10^{-8}, 1]$",
        r"$[10^{-8}, 1]$",
        r"$[2, 256]$",
        r"$[0.4, 1]$",
        r"$[0.4, 1]$",
        r"$[1, 7]$",
        r"$[1, 200]$",
        r"$[64, 511]$",
        r"$[10^{-8}, 10]$",
        r"$[10^{-8}, 10]$",
        r"\{256, 512\}",
        r"$[0.0001, 0.01]$",
        r"$[0.0, 0.9]$",
        r"\{ReLU, Sigmoid, Tanh\}",
        r"\{True, False\}",
        r"\{[32], [64], [128], [32, 32], [64, 64], [128, 128], [64, 128], [128, 64], [64, 128, 64]\}",
    ]
}

distribution = {
    "Distribution": [
        "-",
        "-",
        "-",
        "Log-uniform",
        "Log-uniform",
        "Discrete uniform",
        "Uniform",
        "Uniform",
        "Discrete uniform",
        "Discrete uniform",
        "Discrete uniform",
        "Log-uniform",
        "Log-uniform",
        "Categorical",
        "Log-uniform",
        "Uniform",
        "Categorical",
        "Categorical",
        "Categorical",
    ]
}

search_space_series = pd.Series(search_space["Search space"], index=hyp_results.index)
distribution_series = pd.Series(distribution["Distribution"], index=hyp_results.index)

hyp_results.insert(0, ("", "Search space"), search_space_series)
hyp_results.insert(1, ("", "Distribution"), distribution_series)


for model in ["RUMBoost", "TasteNet", "GBDT", "DNN"]:
    for func_int in ["True", "False"]:
        for func_params in ["True", "False"]:
            if model in ["GBDT", "DNN"] and func_params == "True":
                continue
            results_dict = pd.read_pickle(
                f"{path_to_results}{model}/best_params_fi{func_int}_fp{func_params}.pkl"
            )
            results = pd.DataFrame(results_dict.values(), index=results_dict.keys())

            hyp_results.loc[
                results.index,
                (
                    model,
                    (
                        "Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            "Functional intercept only"
                            if func_int == "True"
                            else (
                                "Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = results.values.reshape(-1)
            if func_int == "False" and func_params == "False" and model in ["RUMBoost", "TasteNet"]:
                hyp_results.loc["dropout", (model, "No functional effects")] = 0
                hyp_results.loc["batch_norm", (model, "No functional effects")] = "False"
                hyp_results.loc["layer_sizes", (model, "No functional effects")] = "-"
                hyp_results.loc["act_func", (model, "No functional effects")] = "-"

for model in ["RUMBoost", "TasteNet"]:
    for func_int in ["True", "False"]:
        for func_params in ["True", "False"]:
            opt_and_cel = pd.read_table(
                f"{path_to_results}{model}/hyper_search_info_fi{func_int}_fp{func_params}.txt",
                header=None,
                index_col=0,
            )
            opt_and_cel_dict = {}
            for element in opt_and_cel.index.to_list():
                ind_and_value = element.split(":")
                opt_and_cel_dict[ind_and_value[0]] = float(ind_and_value[1].strip())
            opt_and_cel = pd.DataFrame(
                opt_and_cel_dict.values(),
                index=opt_and_cel_dict.keys(),
                columns=["values"],
            )
            hyp_results.loc[
                "Time [s]",
                (
                    model,
                    (
                        "Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            "Functional intercept only"
                            if func_int == "True"
                            else (
                                "Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = opt_and_cel.loc["Optimisation time"].values.round(0)
            hyp_results.loc[
                "Validation MCEL",
                (
                    model,
                    (
                        f"Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            f"Functional intercept only"
                            if func_int == "True"
                            else (
                                f"Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = opt_and_cel.loc["Best value"].values.round(3)

hyp_results = hyp_results.rename(index={"best_iteration": "Best iteration/epoch"})
hyp_results = hyp_results.fillna("-")
hyp_results.loc["learning_rate", ("RUMBoost")] = 0.1
hyp_results.loc["Best iteration/epoch", ("GBDT")] = 3000

In [19]:
hyp_results

                                                                            \
                                                              Search space
Validation MCEL                                                          -
Time [s]                                                                 -
Best iteration/epoch                 Max 3000 iterations \slash 200 epochs
lambda_l1                                                   $[10^{-8}, 1]$
lambda_l2                                                   $[10^{-8}, 1]$
num_leaves                                                      $[2, 256]$
feature_fraction                                                $[0.4, 1]$
bagging_fraction                                                $[0.4, 1]$
bagging_freq                                                      $[1, 7]$
min_data_in_leaf                                                $[1, 200]$
max_bin                                                        $[64, 511]$
min_sum_hessian_in_leaf                                    $[10^{-8}, 10]$
min_gain_to_split                                          $[10^{-8}, 10]$
batch_size                                                    \{256, 512\}
learning_rate                                             $[0.0001, 0.01]$
dropout                                                       $[0.0, 0.9]$
act_func                                           \{ReLU, Sigmoid, Tanh\}
batch_norm                                                 \{True, False\}
layer_sizes              \{[32], [64], [128], [32, 32], [64, 64], [128,...

                                                                 RUMBoost  \
                             Distribution Functional intercept and slopes
Validation MCEL                         -                           0.639
Time [s]                                -                           807.0
Best iteration/epoch                    -                           797.0
lambda_l1                     Log-uniform                        0.000009
lambda_l2                     Log-uniform                             0.0
num_leaves               Discrete uniform                           150.0
feature_fraction                  Uniform                        0.892049
bagging_fraction                  Uniform                         0.99951
bagging_freq             Discrete uniform                             4.0
min_data_in_leaf         Discrete uniform                            62.0
max_bin                  Discrete uniform                           426.0
min_sum_hessian_in_leaf       Log-uniform                        0.257508
min_gain_to_split             Log-uniform                        0.003281
batch_size                    Categorical                               -
learning_rate                 Log-uniform                             0.1
dropout                           Uniform                               -
act_func                      Categorical                               -
batch_norm                    Categorical                               -
layer_sizes                   Categorical                               -

                                                                          \
                        Functional slopes only Functional intercept only
Validation MCEL                          0.695                     0.633
Time [s]                                 770.0                     219.0
Best iteration/epoch                     785.0                     399.0
lambda_l1                             0.000373                  0.053499
lambda_l2                             0.002573                  0.000041
num_leaves                                77.0                     244.0
feature_fraction                      0.768465                  0.677433
bagging_fraction                       0.87907                  0.442821
bagging_freq                               6.0                       7.0
min_data_in_leaf                         108.0                      39.0
max_bin                                  270.0                     272.0
min_sum_hessian_in_leaf               0.000214                  0.000001
min_gain_to_split                     0.001512                       0.0
batch_size                                   -                         -
learning_rate                              0.1                       0.1
dropout                                      -                         -
act_func                                     -                         -
batch_norm                                   -                         -
layer_sizes                                  -                         -

                                                                     TasteNet  \
                        No functional effects Functional intercept and slopes
Validation MCEL                         0.768                           0.608
Time [s]                                129.0                           816.0
Best iteration/epoch                    960.0                            65.0
lambda_l1                            0.000038                             0.0
lambda_l2                            0.000345                        0.000003
num_leaves                              165.0                               -
feature_fraction                      0.40305                               -
bagging_fraction                     0.999173                               -
bagging_freq                              2.0                               -
min_data_in_leaf                         32.0                               -
max_bin                                 282.0                               -
min_sum_hessian_in_leaf              0.000001                               -
min_gain_to_split                    0.001148                               -
batch_size                                  -                             512
learning_rate                             0.1                        0.006663
dropout                                     0                        0.067428
act_func                                    -                         sigmoid
batch_norm                              False                            True
layer_sizes                                 -                         64, 128

                                                                          \
                        Functional slopes only Functional intercept only
Validation MCEL                          0.638                     0.675
Time [s]                                 697.0                    1327.0
Best iteration/epoch                      72.0                     135.0
lambda_l1                             0.069202                  0.000001
lambda_l2                             0.000027                       0.0
num_leaves                                   -                         -
feature_fraction                             -                         -
bagging_fraction                             -                         -
bagging_freq                                 -                         -
min_data_in_leaf                             -                         -
max_bin                                      -                         -
min_sum_hessian_in_leaf                      -                         -
min_gain_to_split                            -                         -
batch_size                                 512                       256
learning_rate                         0.007833                  0.007715
dropout                               0.116595                  0.183591
act_func                                  relu                   sigmoid
batch_norm                                True                     False
layer_sizes                        64, 128, 64                   128, 64

                                                                   GBDT  \
                        No functional effects Functional intercept only
Validation MCEL                         0.836                         -
Time [s]                               1123.0                         -
Best iteration/epoch                    169.0                      3000
lambda_l1                            0.000021                  0.000002
lambda_l2                             0.00088                  0.014567
num_leaves                                  -                     112.0
feature_fraction                            -                  0.689312
bagging_fraction                            -                  0.604491
bagging_freq                                -                       6.0
min_data_in_leaf                            -                      14.0
max_bin                                     -                     268.0
min_sum_hessian_in_leaf                     -                  0.085392
min_gain_to_split                           -                       0.0
batch_size                                512                         -
learning_rate                        0.009131                   0.00192
dropout                                     0                         -
act_func                                    -                         -
batch_norm                              False                         -
layer_sizes                                 -                         -

                                                                    DNN  \
                        No functional effects Functional intercept only
Validation MCEL                             -                         -
Time [s]                                    -                         -
Best iteration/epoch                     3000                     100.0
lambda_l1                                 0.0                  0.000045
lambda_l2                            0.000001                  0.000001
num_leaves                              249.0                         -
feature_fraction                     0.500769                         -
bagging_fraction                     0.478012                         -
bagging_freq                              1.0                         -
min_data_in_leaf                          6.0                         -
max_bin                                 104.0                         -
min_sum_hessian_in_leaf              0.000001                         -
min_gain_to_split                    0.651826                         -
batch_size                                  -                       512
learning_rate                        0.002004                  0.003996
dropout                                     -                  0.219341
act_func                                    -                      tanh
batch_norm                                  -                      True
layer_sizes                                 -               64, 128, 64


                        No functional effects
Validation MCEL                             -
Time [s]                                    -
Best iteration/epoch                     47.0
lambda_l1                                 0.0
lambda_l2                                 0.0
num_leaves                                  -
feature_fraction                            -
bagging_fraction                            -
bagging_freq                                -
min_data_in_leaf                            -
max_bin                                     -
min_sum_hessian_in_leaf                     -
min_gain_to_split                           -
batch_size                                512
learning_rate                        0.007479
dropout                              0.177657
act_func                                 tanh
batch_norm                               True
layer_sizes                       64, 128, 64

In [20]:
hyp_results[["GBDT", "DNN"]]

                                             GBDT                        \
                        Functional intercept only No functional effects
Validation MCEL                                 -                     -
Time [s]                                        -                     -
Best iteration/epoch                         3000                  3000
lambda_l1                                0.000002                   0.0
lambda_l2                                0.014567              0.000001
num_leaves                                  112.0                 249.0
feature_fraction                         0.689312              0.500769
bagging_fraction                         0.604491              0.478012
bagging_freq                                  6.0                   1.0
min_data_in_leaf                             14.0                   6.0
max_bin                                     268.0                 104.0
min_sum_hessian_in_leaf                  0.085392              0.000001
min_gain_to_split                             0.0              0.651826
batch_size                                      -                     -
learning_rate                             0.00192              0.002004
dropout                                         -                     -
act_func                                        -                     -
batch_norm                                      -                     -
layer_sizes                                     -                     -

                                              DNN
                        Functional intercept only No functional effects
Validation MCEL                                 -                     -
Time [s]                                        -                     -
Best iteration/epoch                        100.0                  47.0
lambda_l1                                0.000045                   0.0
lambda_l2                                0.000001                   0.0
num_leaves                                      -                     -
feature_fraction                                -                     -
bagging_fraction                                -                     -
bagging_freq                                    -                     -
min_data_in_leaf                                -                     -
max_bin                                         -                     -
min_sum_hessian_in_leaf                         -                     -
min_gain_to_split                               -                     -
batch_size                                    512                   512
learning_rate                            0.003996              0.007479
dropout                                  0.219341              0.177657
act_func                                     tanh                  tanh
batch_norm                                   True                  True
layer_sizes                           64, 128, 64           64, 128, 64

In [21]:
hyp_results.to_latex(
    "results/SwissMetro/hyperparameter_results.tex",
    index=True,
    float_format="%.3f",
    escape=False,
    column_format="l" + "r" * (len(hyp_results.columns) - 1),
)

In [22]:
import os
import pandas as pd

path_to_results = os.getcwd() + "/results/LPMC/"

multi_columns = pd.MultiIndex.from_product(
    [
        ["RUMBoost", "TasteNet"],
        [
            "Functional intercept and slopes",
            "Functional slopes only",
            "Functional intercept only",
            "No functional effects",
        ],
    ],
)

indices = [
    "Validation MCEL",
    "Time [s]",
    "best_iteration",
    "lambda_l1",
    "lambda_l2",
    "num_leaves",
    "feature_fraction",
    "bagging_fraction",
    "bagging_freq",
    "min_data_in_leaf",
    "max_bin",
    "min_sum_hessian_in_leaf",
    "min_gain_to_split",
    "batch_size",
    "learning_rate",
    "dropout",
    "act_func",
    "batch_norm",
    "layer_sizes",
]

hyp_results = pd.DataFrame({}, columns=multi_columns, index=indices)

search_space = {
    "Search space": [
        "-",
        "-",
        r"Max 3000 iterations \slash 200 epochs",
        r"$[10^{-8}, 1]$",
        r"$[10^{-8}, 1]$",
        r"$[2, 256]$",
        r"$[0.4, 1]$",
        r"$[0.4, 1]$",
        r"$[1, 7]$",
        r"$[1, 200]$",
        r"$[64, 511]$",
        r"$[10^{-8}, 10]$",
        r"$[10^{-8}, 10]$",
        r"\{256, 512\}",
        r"$[0.0001, 0.01]$",
        r"$[0.0, 0.9]$",
        r"\{ReLU, Sigmoid, Tanh\}",
        r"\{True, False\}",
        r"\{[32], [64], [128], [32, 32], [64, 64], [128, 128], [64, 128], [128, 64], [64, 128, 64]\}",
    ]
}

distribution = {
    "Distribution": [
        "-",
        "-",
        "-",
        "Log-uniform",
        "Log-uniform",
        "Discrete uniform",
        "Uniform",
        "Uniform",
        "Discrete uniform",
        "Discrete uniform",
        "Discrete uniform",
        "Log-uniform",
        "Log-uniform",
        "Categorical",
        "Log-uniform",
        "Uniform",
        "Categorical",
        "Categorical",
        "Categorical",
    ]
}

search_space_series = pd.Series(search_space["Search space"], index=hyp_results.index)
distribution_series = pd.Series(distribution["Distribution"], index=hyp_results.index)

hyp_results.insert(0, ("", "Search space"), search_space_series)
hyp_results.insert(1, ("", "Distribution"), distribution_series)


for model in ["RUMBoost", "TasteNet", "GBDT", "DNN"]:
    for func_int in ["True", "False"]:
        for func_params in ["True", "False"]:
            if model in ["GBDT", "DNN"] and func_params == "True":
                continue
            results_dict = pd.read_pickle(
                f"{path_to_results}{model}/best_params_fi{func_int}_fp{func_params}.pkl"
            )
            results = pd.DataFrame(results_dict.values(), index=results_dict.keys())

            hyp_results.loc[
                results.index,
                (
                    model,
                    (
                        "Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            "Functional intercept only"
                            if func_int == "True"
                            else (
                                "Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = results.values.reshape(-1)
            if func_int == "False" and func_params == "False" and model in ["RUMBoost", "TasteNet"]:
                hyp_results.loc["dropout", (model, "No functional effects")] = 0
                hyp_results.loc["batch_norm", (model, "No functional effects")] = "False"
                hyp_results.loc["layer_sizes", (model, "No functional effects")] = "-"
                hyp_results.loc["act_func", (model, "No functional effects")] = "-"

for model in ["RUMBoost", "TasteNet"]:
    for func_int in ["True", "False"]:
        for func_params in ["True", "False"]:
            opt_and_cel = pd.read_table(
                f"{path_to_results}{model}/hyper_search_info_fi{func_int}_fp{func_params}.txt",
                header=None,
                index_col=0,
            )
            opt_and_cel_dict = {}
            for element in opt_and_cel.index.to_list():
                ind_and_value = element.split(":")
                opt_and_cel_dict[ind_and_value[0]] = float(ind_and_value[1].strip())
            opt_and_cel = pd.DataFrame(
                opt_and_cel_dict.values(),
                index=opt_and_cel_dict.keys(),
                columns=["values"],
            )
            hyp_results.loc[
                "Time [s]",
                (
                    model,
                    (
                        "Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            "Functional intercept only"
                            if func_int == "True"
                            else (
                                "Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = opt_and_cel.loc["Optimisation time"].values.round(0)
            hyp_results.loc[
                "Validation MCEL",
                (
                    model,
                    (
                        f"Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            f"Functional intercept only"
                            if func_int == "True"
                            else (
                                f"Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = opt_and_cel.loc["Best value"].values.round(3)

hyp_results = hyp_results.rename(index={"best_iteration": "Best iteration/epoch"})
hyp_results = hyp_results.fillna("-")
hyp_results.loc["learning_rate", ("RUMBoost")] = 0.05
hyp_results.loc["Best iteration/epoch", ("GBDT")] = 3000

In [23]:
hyp_results

                                                                            \
                                                              Search space
Validation MCEL                                                          -
Time [s]                                                                 -
Best iteration/epoch                 Max 3000 iterations \slash 200 epochs
lambda_l1                                                   $[10^{-8}, 1]$
lambda_l2                                                   $[10^{-8}, 1]$
num_leaves                                                      $[2, 256]$
feature_fraction                                                $[0.4, 1]$
bagging_fraction                                                $[0.4, 1]$
bagging_freq                                                      $[1, 7]$
min_data_in_leaf                                                $[1, 200]$
max_bin                                                        $[64, 511]$
min_sum_hessian_in_leaf                                    $[10^{-8}, 10]$
min_gain_to_split                                          $[10^{-8}, 10]$
batch_size                                                    \{256, 512\}
learning_rate                                             $[0.0001, 0.01]$
dropout                                                       $[0.0, 0.9]$
act_func                                           \{ReLU, Sigmoid, Tanh\}
batch_norm                                                 \{True, False\}
layer_sizes              \{[32], [64], [128], [32, 32], [64, 64], [128,...

                                                                 RUMBoost  \
                             Distribution Functional intercept and slopes
Validation MCEL                         -                           0.663
Time [s]                                -                          2950.0
Best iteration/epoch                    -                           710.0
lambda_l1                     Log-uniform                             0.0
lambda_l2                     Log-uniform                        0.000005
num_leaves               Discrete uniform                             3.0
feature_fraction                  Uniform                        0.674864
bagging_fraction                  Uniform                        0.537023
bagging_freq             Discrete uniform                             1.0
min_data_in_leaf         Discrete uniform                           109.0
max_bin                  Discrete uniform                           406.0
min_sum_hessian_in_leaf       Log-uniform                        0.003396
min_gain_to_split             Log-uniform                        0.000001
batch_size                    Categorical                               -
learning_rate                 Log-uniform                            0.05
dropout                           Uniform                               -
act_func                      Categorical                               -
batch_norm                    Categorical                               -
layer_sizes                   Categorical                               -

                                                                          \
                        Functional slopes only Functional intercept only
Validation MCEL                          0.671                     0.644
Time [s]                                1635.0                     449.0
Best iteration/epoch                     617.0                     571.0
lambda_l1                                  0.0                  0.000003
lambda_l2                             0.011784                   0.61567
num_leaves                                 3.0                      94.0
feature_fraction                      0.453515                  0.915938
bagging_fraction                      0.812676                  0.862419
bagging_freq                               3.0                       5.0
min_data_in_leaf                         187.0                     140.0
max_bin                                  222.0                     321.0
min_sum_hessian_in_leaf               0.000042                  0.020131
min_gain_to_split                     0.000006                  2.004776
batch_size                                   -                         -
learning_rate                             0.05                      0.05
dropout                                      -                         -
act_func                                     -                         -
batch_norm                                   -                         -
layer_sizes                                  -                         -

                                                                     TasteNet  \
                        No functional effects Functional intercept and slopes
Validation MCEL                         0.809                           0.653
Time [s]                                296.0                          6634.0
Best iteration/epoch                    886.0                           110.0
lambda_l1                            0.000001                        0.000764
lambda_l2                            0.000001                             0.0
num_leaves                              236.0                               -
feature_fraction                     0.978449                               -
bagging_fraction                      0.63371                               -
bagging_freq                              2.0                               -
min_data_in_leaf                         61.0                               -
max_bin                                 474.0                               -
min_sum_hessian_in_leaf              3.082852                               -
min_gain_to_split                    0.001117                               -
batch_size                                  -                             256
learning_rate                            0.05                        0.000478
dropout                                     0                        0.156711
act_func                                    -                            relu
batch_norm                              False                           False
layer_sizes                                 -                          64, 64

                                                                          \
                        Functional slopes only Functional intercept only
Validation MCEL                          0.665                     0.666
Time [s]                                4589.0                    6563.0
Best iteration/epoch                      54.0                     112.0
lambda_l1                             0.012211                       0.0
lambda_l2                             0.000024                  0.030229
num_leaves                                   -                         -
feature_fraction                             -                         -
bagging_fraction                             -                         -
bagging_freq                                 -                         -
min_data_in_leaf                             -                         -
max_bin                                      -                         -
min_sum_hessian_in_leaf                      -                         -
min_gain_to_split                            -                         -
batch_size                                 256                       512
learning_rate                         0.001082                  0.009888
dropout                               0.466752                  0.295135
act_func                                  relu                      relu
batch_norm                                True                     False
layer_sizes                           128, 128                  128, 128

                                                                   GBDT  \
                        No functional effects Functional intercept only
Validation MCEL                         0.835                         -
Time [s]                               4577.0                         -
Best iteration/epoch                     78.0                      3000
lambda_l1                                 0.0                  0.000029
lambda_l2                            0.000014                  0.000098
num_leaves                                  -                      12.0
feature_fraction                            -                  0.911516
bagging_fraction                            -                  0.432779
bagging_freq                                -                       7.0
min_data_in_leaf                            -                     109.0
max_bin                                     -                     247.0
min_sum_hessian_in_leaf                     -                  7.114445
min_gain_to_split                           -                  0.000001
batch_size                                256                         -
learning_rate                        0.008377                  0.003492
dropout                                     0                         -
act_func                                    -                         -
batch_norm                              False                         -
layer_sizes                                 -                         -

                                                                    DNN  \
                        No functional effects Functional intercept only
Validation MCEL                             -                         -
Time [s]                                    -                         -
Best iteration/epoch                     3000                      38.0
lambda_l1                             0.00006                       0.0
lambda_l2                            0.010572                  0.130254
num_leaves                               21.0                         -
feature_fraction                     0.803097                         -
bagging_fraction                     0.435548                         -
bagging_freq                              5.0                         -
min_data_in_leaf                        172.0                         -
max_bin                                 337.0                         -
min_sum_hessian_in_leaf                   0.0                         -
min_gain_to_split                         0.0                         -
batch_size                                  -                       256
learning_rate                        0.001746                  0.003732
dropout                                     -                  0.026465
act_func                                    -                      relu
batch_norm                                  -                      True
layer_sizes                                 -                       128


                        No functional effects
Validation MCEL                             -
Time [s]                                    -
Best iteration/epoch                     81.0
lambda_l1                            0.062726
lambda_l2                                 0.0
num_leaves                                  -
feature_fraction                            -
bagging_fraction                            -
bagging_freq                                -
min_data_in_leaf                            -
max_bin                                     -
min_sum_hessian_in_leaf                     -
min_gain_to_split                           -
batch_size                                256
learning_rate                        0.004153
dropout                              0.010604
act_func                                 relu
batch_norm                               True
layer_sizes                            64, 64

In [24]:
hyp_results[["GBDT", "DNN"]]

                                             GBDT                        \
                        Functional intercept only No functional effects
Validation MCEL                                 -                     -
Time [s]                                        -                     -
Best iteration/epoch                         3000                  3000
lambda_l1                                0.000029               0.00006
lambda_l2                                0.000098              0.010572
num_leaves                                   12.0                  21.0
feature_fraction                         0.911516              0.803097
bagging_fraction                         0.432779              0.435548
bagging_freq                                  7.0                   5.0
min_data_in_leaf                            109.0                 172.0
max_bin                                     247.0                 337.0
min_sum_hessian_in_leaf                  7.114445                   0.0
min_gain_to_split                        0.000001                   0.0
batch_size                                      -                     -
learning_rate                            0.003492              0.001746
dropout                                         -                     -
act_func                                        -                     -
batch_norm                                      -                     -
layer_sizes                                     -                     -

                                              DNN
                        Functional intercept only No functional effects
Validation MCEL                                 -                     -
Time [s]                                        -                     -
Best iteration/epoch                         38.0                  81.0
lambda_l1                                     0.0              0.062726
lambda_l2                                0.130254                   0.0
num_leaves                                      -                     -
feature_fraction                                -                     -
bagging_fraction                                -                     -
bagging_freq                                    -                     -
min_data_in_leaf                                -                     -
max_bin                                         -                     -
min_sum_hessian_in_leaf                         -                     -
min_gain_to_split                               -                     -
batch_size                                    256                   256
learning_rate                            0.003732              0.004153
dropout                                  0.026465              0.010604
act_func                                     relu                  relu
batch_norm                                   True                  True
layer_sizes                                   128                64, 64

In [25]:
hyp_results.to_latex(
    "results/LPMC/hyperparameter_results.tex",
    index=True,
    float_format="%.3f",
    escape=False,
    column_format="l" + "r" * (len(hyp_results.columns) - 1),
)

# Synthetic experiment

In [26]:
index_pd = ["FI-RUMBoost", "FI-DNN", "Random Intercept"] 

benchmark_table = pd.DataFrame({},
    columns=["MAE - Train", "MAE - Test", "CEL - Train", "CEL - Test", "Comput. time [s]"],
    index=index_pd,
)



for dataset in ["synthetic"]:
    path_to_results = os.getcwd() + f"/results/{dataset}/"
    for model in ["RUMBoost", "TasteNet", "MixedEffect"]:
        for func_int in ["True"]:
            for func_params in ["False"]:
                results = pd.read_csv(
                    f"{path_to_results}{model}/results_dict_fi{func_int}_fp{func_params}.csv"
                )
                if model == "RUMBoost":
                    ind = "FI-RUMBoost"
                elif model == "TasteNet":
                    ind = "FI-DNN"
                elif model == "MixedEffect":
                    ind = "Random Intercept"
                results["mae_train"] = (results["L1_distance_train_class_0"] + results["L1_distance_train_class_1"] + results["L1_distance_train_class_2"]) / (3 * 100000)
                results["mae_test"] = (results["L1_distance_test_class_0"] + results["L1_distance_test_class_1"] + results["L1_distance_test_class_2"]) / (3 * 20000)
                benchmark_table.loc[ind] = results[["mae_train", "mae_test", "train_loss", "loss_test", "train_time"]].values.round(3)
                benchmark_table["Comput. time [s]"] = benchmark_table["Comput. time [s]"].astype(float).round(2)

benchmark_table

,MAE - Train,MAE - Test,CEL - Train,CEL - Test,Comput. time [s]
FI-RUMBoost,0.047,0.047,1.343,1.344,1.32
FI-DNN,0.039,0.04,1.345,1.344,45.51
Random Intercept,0.289,0.112,1.35,1.349,45.78

In [27]:
benchmark_table.to_latex("results/synthetic/benchmark_table.tex", index=True, float_format="%.3f", escape=False, column_format="lrrrrr",caption="MAE between recovered and true functional intercepts, negative cross-entropy loss on train and test set, and computational time. The MAE is averaged over the three class intercepts.",label="tab:synthetic_benchmark", bold_rows=True, position="htbp")

In [28]:
import os
import pandas as pd

path_to_results = os.getcwd() + "/results/synthetic/"

multi_columns = pd.MultiIndex.from_product(
    [
        ["RUMBoost", "TasteNet"],
        [
            "Functional intercept only",
        ],
    ],
)

indices = [
    "Validation MCEL",
    "Time [s]",
    "best_iteration",
    "lambda_l1",
    "lambda_l2",
    "num_leaves",
    "feature_fraction",
    "bagging_fraction",
    "bagging_freq",
    "min_data_in_leaf",
    "max_bin",
    "min_sum_hessian_in_leaf",
    "min_gain_to_split",
    "batch_size",
    "learning_rate",
    "dropout",
    "act_func",
    "batch_norm",
    "layer_sizes",
]

hyp_results = pd.DataFrame({}, columns=multi_columns, index=indices)

search_space = {
    "Search space": [
        "-",
        "-",
        r"Max 3000 iterations \slash 200 epochs",
        r"$[10^{-8}, 1]$",
        r"$[10^{-8}, 1]$",
        r"$[2, 256]$",
        r"$[0.4, 1]$",
        r"$[0.4, 1]$",
        r"$[1, 7]$",
        r"$[1, 200]$",
        r"$[64, 511]$",
        r"$[10^{-8}, 10]$",
        r"$[10^{-8}, 10]$",
        r"\{256, 512\}",
        r"$[0.0001, 0.01]$",
        r"$[0.0, 0.9]$",
        r"\{ReLU, Sigmoid, Tanh\}",
        r"\{True, False\}",
        r"\{[32], [64], [128], [32, 32], [64, 64], [128, 128], [64, 128], [128, 64], [64, 128, 64]\}",
    ]
}

distribution = {
    "Distribution": [
        "-",
        "-",
        "-",
        "Log-uniform",
        "Log-uniform",
        "Discrete uniform",
        "Uniform",
        "Uniform",
        "Discrete uniform",
        "Discrete uniform",
        "Discrete uniform",
        "Log-uniform",
        "Log-uniform",
        "Categorical",
        "Log-uniform",
        "Uniform",
        "Categorical",
        "Categorical",
        "Categorical",
    ]
}

search_space_series = pd.Series(search_space["Search space"], index=hyp_results.index)
distribution_series = pd.Series(distribution["Distribution"], index=hyp_results.index)

hyp_results.insert(0, ("", "Search space"), search_space_series)
hyp_results.insert(1, ("", "Distribution"), distribution_series)


for model in ["RUMBoost", "TasteNet"]:
    for func_int in ["True"]:
        for func_params in ["False"]:
            results_dict = pd.read_pickle(
                f"{path_to_results}{model}/best_params_fi{func_int}_fp{func_params}.pkl"
            )
            results = pd.DataFrame(results_dict.values(), index=results_dict.keys())

            hyp_results.loc[
                results.index,
                (
                    model,
                    (
                        "Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            "Functional intercept only"
                            if func_int == "True"
                            else (
                                "Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = results.values.reshape(-1)
            if func_int == "False" and func_params == "False":
                hyp_results.loc["dropout", (model, "No functional effects")] = 0
                hyp_results.loc["batch_norm", (model, "No functional effects")] = "False"
                hyp_results.loc["layer_sizes", (model, "No functional effects")] = "-"
                hyp_results.loc["act_func", (model, "No functional effects")] = "-"

for model in ["RUMBoost", "TasteNet"]:
    for func_int in ["True"]:
        for func_params in ["False"]:
            opt_and_cel = pd.read_table(
                f"{path_to_results}{model}/hyper_search_info_fi{func_int}_fp{func_params}.txt",
                header=None,
                index_col=0,
            )
            opt_and_cel_dict = {}
            for element in opt_and_cel.index.to_list():
                ind_and_value = element.split(":")
                opt_and_cel_dict[ind_and_value[0]] = float(ind_and_value[1].strip())
            opt_and_cel = pd.DataFrame(
                opt_and_cel_dict.values(),
                index=opt_and_cel_dict.keys(),
                columns=["values"],
            )
            hyp_results.loc[
                "Time [s]",
                (
                    model,
                    (
                        "Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            "Functional intercept only"
                            if func_int == "True"
                            else (
                                "Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = opt_and_cel.loc["Optimisation time"].values.round(0)
            hyp_results.loc[
                "Validation MCEL",
                (
                    model,
                    (
                        f"Functional intercept and slopes"
                        if func_int == "True" and func_params == "True"
                        else (
                            f"Functional intercept only"
                            if func_int == "True"
                            else (
                                f"Functional slopes only"
                                if func_params == "True"
                                else "No functional effects"
                            )
                        )
                    ),
                ),
            ] = opt_and_cel.loc["Best value"].values.round(3)

hyp_results = hyp_results.rename(index={"best_iteration": "Best iteration/epoch"})
hyp_results = hyp_results.fillna("-")
hyp_results.loc["learning_rate", ("RUMBoost")] = 0.05

In [29]:
hyp_results

                                                                            \
                                                              Search space
Validation MCEL                                                          -
Time [s]                                                                 -
Best iteration/epoch                 Max 3000 iterations \slash 200 epochs
lambda_l1                                                   $[10^{-8}, 1]$
lambda_l2                                                   $[10^{-8}, 1]$
num_leaves                                                      $[2, 256]$
feature_fraction                                                $[0.4, 1]$
bagging_fraction                                                $[0.4, 1]$
bagging_freq                                                      $[1, 7]$
min_data_in_leaf                                                $[1, 200]$
max_bin                                                        $[64, 511]$
min_sum_hessian_in_leaf                                    $[10^{-8}, 10]$
min_gain_to_split                                          $[10^{-8}, 10]$
batch_size                                                    \{256, 512\}
learning_rate                                             $[0.0001, 0.01]$
dropout                                                       $[0.0, 0.9]$
act_func                                           \{ReLU, Sigmoid, Tanh\}
batch_norm                                                 \{True, False\}
layer_sizes              \{[32], [64], [128], [32, 32], [64, 64], [128,...

                                                           RUMBoost  \
                             Distribution Functional intercept only
Validation MCEL                         -                     1.347
Time [s]                                -                     164.0
Best iteration/epoch                    -                     161.0
lambda_l1                     Log-uniform                  0.031654
lambda_l2                     Log-uniform                       0.0
num_leaves               Discrete uniform                       2.0
feature_fraction                  Uniform                  0.660277
bagging_fraction                  Uniform                  0.964188
bagging_freq             Discrete uniform                       5.0
min_data_in_leaf         Discrete uniform                      67.0
max_bin                  Discrete uniform                     336.0
min_sum_hessian_in_leaf       Log-uniform                  0.025614
min_gain_to_split             Log-uniform                  1.178531
batch_size                    Categorical                         -
learning_rate                 Log-uniform                      0.05
dropout                           Uniform                         -
act_func                      Categorical                         -
batch_norm                    Categorical                         -
layer_sizes                   Categorical                         -

                                         TasteNet
                        Functional intercept only
Validation MCEL                             1.347
Time [s]                                   4451.0
Best iteration/epoch                           32
lambda_l1                                0.000033
lambda_l2                                0.000009
num_leaves                                      -
feature_fraction                                -
bagging_fraction                                -
bagging_freq                                    -
min_data_in_leaf                                -
max_bin                                         -
min_sum_hessian_in_leaf                         -
min_gain_to_split                               -
batch_size                                    256
learning_rate                             0.00109
dropout                                  0.062059
act_func                                  sigmoid
batch_norm                                  False
layer_sizes                               128, 64

## Big benchmarks

In [3]:
index_pd = pd.MultiIndex.from_product(
    [
        ["RUMBoost", "TasteNet"],
        ["Functional intercept and slopes", "Functional slopes only", "Functional intercept only","No functional effects"],
    ],
    names=["Model", "Functional effects"],
)

benchmark_table = pd.DataFrame({},
    columns=pd.MultiIndex.from_product(
        [
            ["Datasets"],
            ["With FI and FS", "With FS", "With FI", "Without FI and FS"],
            ["MAE", "CEL"]
        ],
    ),
   index=index_pd,
)

benchmark_table_train = pd.DataFrame({},
    columns=pd.MultiIndex.from_product(
        [
            ["Datasets"],
            ["With FI and FS", "With FS", "With FI", "Without FI and FS"],
            ["MAE", "CEL"]
        ],
    ),
   index=index_pd,
)



for with_int in ["True", "False"]:
    for with_slopes in ["True", "False"]:
        dataset = "synthetic_withint" + with_int + "_withslopes" + with_slopes
        path_to_results = os.getcwd() + f"/results/{dataset}/"
        for model in ["RUMBoost", "TasteNet"]:
            for func_int in ["True", "False"]:
                for func_params in ["True", "False"]:

                    results = pd.read_csv(
                        f"{path_to_results}{model}/results_dict_fi{func_int}_fp{func_params}.csv"
                    )

                    if with_int == "True" and with_slopes == "True":
                        dataset_name = "With FI and FS"
                    elif with_int == "True" and with_slopes == "False":
                        dataset_name = "With FI"
                    elif with_int == "False" and with_slopes == "True":
                        dataset_name = "With FS"
                    else:
                        dataset_name = "Without FI and FS"

                    benchmark_table.loc[
                        (model, f"Functional intercept and slopes" if func_int == "True" and func_params == "True" else
                        f"Functional intercept only" if func_int == "True" else
                        f"Functional slopes only" if func_params == "True" else
                        "No functional effects"),
                        ("Datasets", [dataset_name], "CEL"),
                    ] = results[["loss_test"]].values.round(3)

                    benchmark_table.loc[
                        (model, f"Functional intercept and slopes" if func_int == "True" and func_params == "True" else
                        f"Functional intercept only" if func_int == "True" else
                        f"Functional slopes only" if func_params == "True" else
                        "No functional effects"),
                        ("Datasets", [dataset_name], "MAE"),
                    ] = results[["avg_l1_dist_test"]].values.round(3)


                    benchmark_table_train.loc[
                        (model, f"Functional intercept and slopes" if func_int == "True" and func_params == "True" else
                        f"Functional intercept only" if func_int == "True" else
                        f"Functional slopes only" if func_params == "True" else
                        "No functional effects"),
                        ("Datasets", [dataset_name], "CEL"),
                    ] = results[["train_loss"]].values.round(3)

                    benchmark_table_train.loc[
                        (model, f"Functional intercept and slopes" if func_int == "True" and func_params == "True" else
                        f"Functional intercept only" if func_int == "True" else
                        f"Functional slopes only" if func_params == "True" else
                        "No functional effects"),
                        ("Datasets", [dataset_name], "MAE"),
                    ] = results[["avg_l1_dist"]].values.round(3)

                    # benchmark_table.loc[
                    #     (model, f"Functional intercept and slopes" if func_int == "True" and func_params == "True" else
                    #     f"Functional intercept only" if func_int == "True" else
                    #     f"Functional slopes only" if func_params == "True" else
                    #     "No functional effects"),
                    #     ("Datasets", [dataset_name], "MAPE"),
                    # ] = results[["mape_test"]].values.round(3)

                    # benchmark_table_train.loc[
                    #     (model, f"Functional intercept and slopes" if func_int == "True" and func_params == "True" else
                    #     f"Functional intercept only" if func_int == "True" else
                    #     f"Functional slopes only" if func_params == "True" else
                    #     "No functional effects"),
                    #     ("Datasets", [dataset_name], "MAPE"),
                    # ] = results[["mape"]].values.round(3)


benchmark_table

                                               Datasets                        \
                                         With FI and FS        With FS
                                                    MAE    CEL     MAE    CEL
Model    Functional effects
RUMBoost Functional intercept and slopes          0.075  1.359   0.089  1.375
         Functional slopes only                   0.144   1.36   0.173  1.374
         Functional intercept only                0.136  1.359   0.129  1.375
         No functional effects                    0.325  1.363    0.36  1.378
TasteNet Functional intercept and slopes          0.062  1.359   0.048  1.374
         Functional slopes only                   0.172  1.359   0.094  1.375
         Functional intercept only                0.099  1.359     0.1  1.375
         No functional effects                    0.197  1.362    0.08  1.377

                                                                           \
                                         With FI        Without FI and FS
                                             MAE    CEL               MAE
Model    Functional effects
RUMBoost Functional intercept and slopes   0.064  1.344             0.061
         Functional slopes only            0.137  1.345             0.175
         Functional intercept only         0.093  1.344             0.133
         No functional effects             0.332   1.35             0.431
TasteNet Functional intercept and slopes   0.214  1.351             0.058
         Functional slopes only            0.156  1.345             0.058
         Functional intercept only         0.026  1.344             0.032
         No functional effects             0.123   1.35              0.03



                                            CEL
Model    Functional effects
RUMBoost Functional intercept and slopes  1.359
         Functional slopes only           1.359
         Functional intercept only        1.359
         No functional effects            1.359
TasteNet Functional intercept and slopes  1.358
         Functional slopes only           1.359
         Functional intercept only        1.359
         No functional effects            1.359

In [4]:
benchmark_table_train

                                               Datasets                        \
                                         With FI and FS        With FS
                                                    MAE    CEL     MAE    CEL
Model    Functional effects
RUMBoost Functional intercept and slopes          0.067  1.357   0.081  1.373
         Functional slopes only                   0.141   1.36   0.166  1.372
         Functional intercept only                0.131  1.359   0.129  1.374
         No functional effects                    0.335  1.363   0.362  1.377
TasteNet Functional intercept and slopes          0.057   1.36    0.04  1.375
         Functional slopes only                   0.165  1.361   0.087  1.376
         Functional intercept only                0.095  1.361   0.097  1.376
         No functional effects                     0.19  1.364   0.076  1.377

                                                                           \
                                         With FI        Without FI and FS
                                             MAE    CEL               MAE
Model    Functional effects
RUMBoost Functional intercept and slopes   0.062  1.343             0.061
         Functional slopes only            0.137  1.345             0.174
         Functional intercept only         0.095  1.343             0.134
         No functional effects             0.337   1.35             0.432
TasteNet Functional intercept and slopes   0.214  1.354             0.058
         Functional slopes only            0.152  1.347             0.058
         Functional intercept only         0.026  1.345             0.032
         No functional effects             0.118   1.35              0.03



                                            CEL
Model    Functional effects
RUMBoost Functional intercept and slopes  1.356
         Functional slopes only           1.356
         Functional intercept only        1.355
         No functional effects            1.356
TasteNet Functional intercept and slopes  1.358
         Functional slopes only           1.358
         Functional intercept only        1.358
         No functional effects            1.357

In [5]:
benchmark_table.to_latex("results/benchmark_table_synthetic_big_exp.tex", index=True, float_format="%.3f", escape=False, column_format="lrrrrr",caption="Mean Absolute Error (MAE) between true and recovered functional effects (averaged across observations and effects), and negative cross-entropy loss (CEL) on test set for all possible functional effects models and synthetic datasets.",label="tab:synthetic_big_benchmark", bold_rows=True, position="htbp")

In [6]:
benchmark_table_train.to_latex("results/benchmark_table_synthetic_big_exp_train.tex", index=True, float_format="%.3f", escape=False, column_format="lrrrrr",caption="Mean Absolute Error (MAE) between true and recovered functional effects (averaged across observations and effects), and negative cross-entropy loss (CEL) on train set for all possible functional effects models and synthetic datasets.",label="tab:synthetic_big_benchmark_train", bold_rows=True, position="htbp")